class C:
  try:
    raise Exception("Oops")
  except:
    print "Caught"
